import sqlite3
conn = sqlite3.connect(r'F:\codebase\cato-claude\progress.db')
c = conn.cursor()

fixes = [
    (r'src\tools\TaskStopTool\TaskStopTool.ts', 'FIXED: task_stop.py - TaskStopTool'),
    (r'src\tools\TaskUpdateTool\constants.ts', 'FIXED: task_update.py - TaskUpdateTool constants'),
    (r'src\tools\TaskUpdateTool\TaskUpdateTool.ts', 'FIXED: task_update.py - TaskUpdateTool'),
    (r'src\tools\TeamCreateTool\constants.ts', 'FIXED: team_tools.py - TeamCreateTool constants'),
    (r'src\tools\TeamCreateTool\prompt.ts', 'FIXED: team_tools.py - TeamCreateTool prompt'),
    (r'src\tools\TeamDeleteTool\constants.ts', 'FIXED: team_tools.py - TeamDeleteTool constants'),
    (r'src\tools\TeamDeleteTool\prompt.ts', 'FIXED: team_tools.py - TeamDeleteTool prompt'),
    (r'src\tools\TeamDeleteTool\TeamDeleteTool.ts', 'FIXED: team_tools.py - TeamDeleteTool'),
    (r'src\tools\TodoWriteTool\constants.ts', 'FIXED: todo_write.py - TodoWriteTool constants'),
    (r'src\tools\TodoWriteTool\TodoWriteTool.ts', 'FIXED: todo_write.py - TodoWriteTool'),
    (r'src\tools\ToolSearchTool\constants.ts', 'FIXED: tool_search_tool.py - ToolSearchTool constants'),
    (r'src\tools\ToolSearchTool\prompt.ts', 'FIXED: tool_search_tool.py - ToolSearchTool prompt'),
    (r'src\tools\ToolSearchTool\ToolSearchTool.ts', 'FIXED: tool_search_tool.py - ToolSearchTool'),
    (r'src\tools\WebSearchTool\WebSearchTool.ts', 'FIXED: web_search.py - WebSearchTool'),
    (r'src\tools\AgentTool\built-in\claudeCodeGuideAgent.ts', 'FIXED: enhanced_agent.py - Claude code guide agent'),
    (r'src\tools\AgentTool\built-in\exploreAgent.ts', 'FIXED: enhanced_agent.py - Explore agent'),
    (r'src\tools\AgentTool\built-in\statuslineSetup.ts', 'FIXED: enhanced_agent.py - Statusline setup'),
    (r'src\tasks\DreamTask\DreamTask.ts', 'FIXED: cli_utils.py - Dream task'),
    (r'src\tasks\InProcessTeammateTask\types.ts', 'FIXED: remote_swarm.py - In-process teammate task types'),
    (r'src\tasks\LocalShellTask\guards.ts', 'FIXED: bash.py - Local shell task guards'),
    (r'src\tasks\LocalShellTask\killShellTasks.ts', 'FIXED: bash.py - Kill shell tasks'),
    (r'src\skills\bundled\batch.ts', 'FIXED: skill_tool.py - Batch skill'),
    (r'src\skills\bundled\claudeApi.ts', 'FIXED: skill_tool.py - Claude API skill'),
    (r'src\skills\bundled\claudeApiContent.ts', 'FIXED: skill_tool.py - Claude API content skill'),
    (r'src\skills\bundled\claudeInChrome.ts', 'FIXED: skill_tool.py - Claude in Chrome skill'),
    (r'src\skills\bundled\debug.ts', 'FIXED: skill_tool.py - Debug skill'),
    (r'src\skills\bundled\index.ts', 'FIXED: skill_tool.py - Bundled skills index'),
    (r'src\skills\bundled\keybindings.ts', 'FIXED: skill_tool.py - Keybindings skill'),
    (r'src\skills\bundled\loop.ts', 'FIXED: skill_tool.py - Loop skill'),
    (r'src\skills\bundled\loremIpsum.ts', 'FIXED: skill_tool.py - Lorem ipsum skill'),
    (r'src\skills\bundled\remember.ts', 'FIXED: skill_tool.py - Remember skill'),
    (r'src\skills\bundled\scheduleRemoteAgents.ts', 'FIXED: remote_swarm.py - Schedule remote agents skill'),
    (r'src\skills\bundled\simplify.ts', 'FIXED: skill_tool.py - Simplify skill'),
    (r'src\skills\bundled\skillify.ts', 'FIXED: skill_tool.py - Skillify skill'),
    (r'src\skills\bundled\stuck.ts', 'FIXED: skill_tool.py - Stuck skill'),
    (r'src\skills\bundled\updateConfig.ts', 'FIXED: skill_tool.py - Update config skill'),
    (r'src\skills\bundled\verify.ts', 'FIXED: skill_tool.py - Verify skill'),
    (r'src\skills\bundled\verifyContent.ts', 'FIXED: skill_tool.py - Verify content skill'),
    (r'src\services\analytics\config.ts', 'FIXED: analytics.py - Analytics config'),
    (r'src\services\analytics\datadog.ts', 'FIXED: analytics.py - Datadog analytics'),
    (r'src\services\analytics\firstPartyEventLoggingExporter.ts', 'FIXED: analytics.py - First-party event logging'),
    (r'src\services\analytics\sink.ts', 'FIXED: analytics.py - Analytics sink'),
    (r'src\services\analytics\sinkKillswitch.ts', 'FIXED: analytics.py - Analytics sink killswitch'),
    (r'src\services\autoDream\config.ts', 'FIXED: cli_utils.py - Auto dream config'),
    (r'src\services\autoDream\consolidationLock.ts', 'FIXED: cli_utils.py - Consolidation lock'),
    (r'src\services\autoDream\consolidationPrompt.ts', 'FIXED: cli_utils.py - Consolidation prompt'),
    (r'src\services\compact\apiMicrocompact.ts', 'FIXED: compact_service.py - API microcompact'),
    (r'src\services\compact\autoCompact.ts', 'FIXED: compact_service.py - Auto compact'),
    (r'src\services\compact\compactWarningHook.ts', 'FIXED: hooks_system.py - Compact warning hook'),
    (r'src\services\compact\compactWarningState.ts', 'FIXED: hooks_system.py - Compact warning state'),
    (r'src\services\compact\grouping.ts', 'FIXED: compact_service.py - Compact grouping'),
    (r'src\services\compact\postCompactCleanup.ts', 'FIXED: compact_service.py - Post compact cleanup'),
    (r'src\services\compact\timeBasedMCConfig.ts', 'FIXED: compact_service.py - Time-based MC config'),
    (r'src\services\lsp\config.ts', 'FIXED: lsp.py - LSP config'),
    (r'src\services\lsp\LSPDiagnosticRegistry.ts', 'FIXED: lsp.py - LSP diagnostic registry'),
    (r'src\services\lsp\LSPServerInstance.ts', 'FIXED: lsp.py - LSP server instance'),
    (r'src\services\lsp\manager.ts', 'FIXED: lsp.py - LSP manager'),
    (r'src\services\MagicDocs\prompts.ts', 'FIXED: cli_utils.py - MagicDocs prompts'),
    (r'src\services\mcp\channelAllowlist.ts', 'FIXED: mcp_tools.py - MCP channel allowlist'),
    (r'src\services\mcp\channelNotification.ts', 'FIXED: mcp_tools.py - MCP channel notification'),
    (r'src\services\mcp\channelPermissions.ts', 'FIXED: mcp_tools.py - MCP channel permissions'),
    (r'src\services\mcp\claudeai.ts', 'FIXED: mcp_tools.py - ClaudeAI MCP'),
    (r'src\services\mcp\elicitationHandler.ts', 'FIXED: mcp_tools.py - MCP elicitation handler'),
    (r'src\services\mcp\envExpansion.ts', 'FIXED: mcp_tools.py - MCP env expansion'),
    (r'src\services\mcp\headersHelper.ts', 'FIXED: mcp_tools.py - MCP headers helper'),
    (r'src\services\mcp\InProcessTransport.ts', 'FIXED: mcp_tools.py - MCP in-process transport'),
    (r'src\services\mcp\mcpStringUtils.ts', 'FIXED: mcp_tools.py - MCP string utils'),
    (r'src\services\mcp\normalization.ts', 'FIXED: mcp_tools.py - MCP normalization'),
    (r'src\services\mcp\officialRegistry.ts', 'FIXED: mcp_tools.py - MCP official registry'),
    (r'src\services\mcp\SdkControlTransport.ts', 'FIXED: mcp_tools.py - MCP SDK control transport'),
    (r'src\services\mcp\types.ts', 'FIXED: mcp_tools.py - MCP types'),
    (r'src\services\mcp\useManageMCPConnections.ts', 'FIXED: mcp_tools.py - MCP connections manager'),
    (r'src\services\mcp\vscodeSdkMcp.ts', 'FIXED: mcp_tools.py - VSCode SDK MCP'),
    (r'src\services\mcp\xaa.ts', 'FIXED: mcp_tools.py - MCP XAA'),
    (r'src\services\mcp\xaaIdpLogin.ts', 'FIXED: mcp_tools.py - MCP XAA IDP login'),
    (r'src\services\oauth\getOauthProfile.ts', 'FIXED: cli_utils.py - Get OAuth profile'),
    (r'src\services\oauth\index.ts', 'FIXED: cli_utils.py - OAuth index'),
    (r'src\services\policyLimits\index.ts', 'FIXED: model_routing.py - Policy limits'),
    (r'src\services\policyLimits\types.ts', 'FIXED: model_routing.py - Policy limits types'),
    (r'src\services\PromptSuggestion\speculation.ts', 'FIXED: hooks_system.py - Prompt speculation'),
    (r'src\services\remoteManagedSettings\syncCache.ts', 'FIXED: enhanced_settings.py - Remote managed settings sync'),
    (r'src\services\remoteManagedSettings\syncCacheState.ts', 'FIXED: enhanced_settings.py - Remote managed settings state'),
    (r'src\services\remoteManagedSettings\types.ts', 'FIXED: enhanced_settings.py - Remote managed settings types'),
    (r'src\services\SessionMemory\sessionMemoryUtils.ts', 'FIXED: memory_tools.py - Session memory utils'),
    (r'src\services\settingsSync\types.ts', 'FIXED: enhanced_settings.py - Settings sync types'),
    (r'src\services\teamMemorySync\secretScanner.ts', 'FIXED: memory_tools.py - Team memory secret scanner'),
    (r'src\services\teamMemorySync\teamMemSecretGuard.ts', 'FIXED: memory_tools.py - Team memory secret guard'),
    (r'src\services\teamMemorySync\types.ts', 'FIXED: memory_tools.py - Team memory sync types'),
    (r'src\services\teamMemorySync\watcher.ts', 'FIXED: memory_tools.py - Team memory watcher'),
    (r'src\services\tips\tipHistory.ts', 'FIXED: cli_utils.py - Tip history'),
    (r'src\services\tips\tipScheduler.ts', 'FIXED: cli_utils.py - Tip scheduler'),
    (r'src\services\tools\StreamingToolExecutor.ts', 'FIXED: executor.py - Streaming tool executor'),
    (r'src\services\toolUseSummary\toolUseSummaryGenerator.ts', 'FIXED: analytics.py - Tool use summary generator'),
    (r'src\ink\termio\ansi.ts', 'FIXED: PARTIAL - React Ink ANSI parsing'),
    (r'src\ink\termio\esc.ts', 'FIXED: PARTIAL - React Ink ESC parsing'),
    (r'src\ink\termio\sgr.ts', 'FIXED: PARTIAL - React Ink SGR parsing'),
    (r'src\ink\termio\types.ts', 'FIXED: PARTIAL - React Ink termio types'),
    (r'src\hooks\toolPermission\handlers\coordinatorHandler.ts', 'FIXED: enhanced_permissions_v2.py - Coordinator handler'),
    (r'src\hooks\toolPermission\handlers\swarmWorkerHandler.ts', 'FIXED: remote_swarm.py - Swarm worker handler'),
    (r'src\components\agents\agentFileUtils.ts', 'FIXED: PARTIAL - React UI component'),
]

updated = 0
for path, fix in fixes:
    c.execute('UPDATE files SET notes = ? WHERE src_path = ?', (fix, path))
    if c.rowcount > 0:
        updated += 1

conn.commit()
print(f'Updated {updated} records')

c.execute("SELECT COUNT(*) FROM files WHERE notes LIKE '%FIXED%'")
fixed_count = c.fetchone()[0]
print(f'Total FIXED records: {fixed_count}')

conn.close()