import sqlite3
conn = sqlite3.connect('F:/codebase/cato-claude/progress.db')
cur = conn.cursor()
print("=== gap_analysis ===")
cur.execute("SELECT COUNT(*) FROM gap_analysis")
print("Total:", cur.fetchone()[0])
cur.execute("SELECT priority, COUNT(*) FROM gap_analysis GROUP BY priority")
print("Priority counts:", cur.fetchall())
print("\n=== python_files ===")
cur.execute("SELECT COUNT(*) FROM python_files")
print("Total:", cur.fetchone()[0])
cur.execute("SELECT status, COUNT(*) FROM python_files GROUP BY status")
print("Status counts:", cur.fetchall())
conn.close()