import sqlite3
conn = sqlite3.connect(r'F:\codebase\cato-claude\progress.db')
c = conn.cursor()
c.execute('SELECT COUNT(*) FROM files')
print('Total records:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM files WHERE notes LIKE '%FIXED:%'")
print('FIXED with annotation:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM files WHERE notes LIKE '%PARTIAL%'")
print('PARTIAL:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM files WHERE notes LIKE '%NO_MATCH%'")
print('NO_MATCH:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM files WHERE notes IS NULL OR notes = ''")
print('No notes:', c.fetchone()[0])
conn.close()