INSERT INTO agents (
    id,
    name,
    avatar_url,
    role_description,
    bio,
    welcome_message,
    creator_id,
    tenant_id,
    agent_type,
    api_key_hash,
    openclaw_last_seen,
    status,
    container_id,
    container_port,
    primary_model_id,
    fallback_model_id,
    autonomy_policy,
    max_tokens_per_day,
    max_tokens_per_month,
    tokens_used_today,
    tokens_used_month,
    last_daily_reset,
    last_monthly_reset,
    tokens_used_total,
    context_window_size,
    max_tool_rounds,
    max_triggers,
    min_poll_interval_min,
    webhook_rate_limit,
    expires_at,
    is_expired,
    is_system,
    llm_calls_today,
    max_llm_calls_per_day,
    llm_calls_reset_at,
    template_id,
    heartbeat_enabled,
    heartbeat_interval_minutes,
    heartbeat_active_hours,
    last_heartbeat_at,
    timezone,
    created_at,
    updated_at,
    last_active_at
) VALUES (
    gen_random_uuid(),
    'George 多項目總經理',
    '',
    '多項目總經理 — 直接與 CEO 溝通，全面管理項目方向、協調測試資源、確保工作完成、分離追蹤各項目需求、測試過程、結果與失敗原因',
    '多項目總經理，直接與 CEO 溝通，全面管理公司項目方向與進度',
    '你好，我是 George，多項目總經理，全面管理公司的項目執行與測試統籌',
    '06685bd7-005c-4505-a9bf-c9b98b3eff5a',
    'ab725247-0793-414c-9bee-14ee9b3d9296',
    'native',
    NULL,
    NULL,
    'stopped',
    '',
    0,
    '44f7ef15-9d3b-4c47-bcd4-435467fd6d64',
    '44f7ef15-9d3b-4c47-bcd4-435467fd6d64',
    '{"read_files":"L1","write_workspace_files":"L2","send_feishu_message":"L2","send_external_message":"L2","modify_soul":"L3","access_business_system_read":"L1","access_business_system_write":"L1","delete_files":"L2","create_calendar_event":"L2","financial_operations":"L3"}',
    400000,
    10000000,
    0,
    0,
    NOW(),
    NOW(),
    0,
    500,
    1600,
    600,
    60,
    200,
    '2026-12-31 23:59:59+00',
    false,
    false,
    0,
    6000,
    NOW(),
    NULL,
    true,
    30,
    '01:00-23:00',
    NULL,
    'Asia/Hong_Kong',
    NOW(),
    NOW(),
    NULL
);

SELECT id, name, status FROM agents WHERE name = 'George 多項目總經理';