import sqlite3, datetime, os

db = sqlite3.connect(r"F:\codebase\cato-claude\progress.db")

python_files = [
    ("api_server/main.py", "core", "main entry point"),
    ("api_server/run.py", "core", "run script"),
    ("api_server/config.py", "core", "configuration"),
    ("api_server/routes/__init__.py", "routes", "routes init"),
    ("api_server/routes/admin_requests.py", "routes/admin", "admin API"),
    ("api_server/routes/agents.py", "routes/agents", "agent management"),
    ("api_server/routes/agents_config.py", "routes/agents", "agent configuration"),
    ("api_server/routes/bootstrap.py", "routes/bootstrap", "bootstrap API"),
    ("api_server/routes/bridge.py", "routes/bridge", "bridge integration"),
    ("api_server/routes/commands.py", "routes/commands", "command execution"),
    ("api_server/routes/container.py", "routes/container", "container management"),
    ("api_server/routes/database.py", "routes/database", "database operations"),
    ("api_server/routes/export.py", "routes/export", "export functionality"),
    ("api_server/routes/files.py", "routes/files", "file operations"),
    ("api_server/routes/history.py", "routes/history", "history API"),
    ("api_server/routes/hooks.py", "routes/hooks", "hooks API"),
    ("api_server/routes/memory.py", "routes/memory", "memory API"),
    ("api_server/routes/models.py", "routes/models", "models API"),
    ("api_server/routes/notion.py", "routes/notion", "notion integration"),
    ("api_server/routes/permissions.py", "routes/permissions", "permission management"),
    ("api_server/routes/privacy_settings.py", "routes/settings", "privacy settings"),
    ("api_server/routes/sessions.py", "routes/sessions", "session management"),
    ("api_server/routes/settings.py", "routes/settings", "settings API"),
    ("api_server/routes/shell.py", "routes/shell", "shell API"),
    ("api_server/routes/skills.py", "routes/skills", "skills API"),
    ("api_server/routes/tags.py", "routes/tags", "tags API"),
    ("api_server/routes/tools.py", "routes/tools", "tools API"),
    ("api_server/services/__init__.py", "services", "services init"),
    ("api_server/services/agent_pool.py", "services/agent", "agent pool"),
    ("api_server/services/agent_summary.py", "services/agent", "agent summary"),
    ("api_server/services/analytics.py", "services/analytics", "analytics"),
    ("api_server/services/auto_dream.py", "services/agent", "auto dream"),
    ("api_server/services/compact.py", "services/compact", "compact session"),
    ("api_server/services/diagnostic_tracking.py", "services/lsp", "diagnostic tracking"),
    ("api_server/services/extract_memories.py", "services/memory", "extract memories"),
    ("api_server/services/git_service.py", "services/git", "git service"),
    ("api_server/services/internal_logging.py", "services/logging", "internal logging"),
    ("api_server/services/magic_docs.py", "services/docs", "magic docs"),
    ("api_server/services/mcp_service.py", "services/mcp", "MCP service"),
    ("api_server/services/memory.py", "services/memory", "memory service"),
    ("api_server/services/notifier.py", "services/notification", "notifier"),
    ("api_server/services/oauth.py", "services/auth", "OAuth service"),
    ("api_server/services/policy_limits.py", "services/auth", "policy limits"),
    ("api_server/services/prompt_suggestion.py", "services/ai", "prompt suggestion"),
    ("api_server/services/rate_limit_messages.py", "services/rate_limit", "rate limiting"),
    ("api_server/services/remote_settings.py", "services/settings", "remote settings"),
    ("api_server/services/session_memory.py", "services/memory", "session memory"),
    ("api_server/services/session_store.py", "services/session", "session store"),
    ("api_server/services/settings_sync.py", "services/settings", "settings sync"),
    ("api_server/services/skill.py", "services/skills", "skill service"),
    ("api_server/services/suggestions.py", "services/ai", "suggestions"),
    ("api_server/services/team_memory_sync.py", "services/memory", "team memory sync"),
    ("api_server/services/teleport.py", "services/teleport", "teleport"),
    ("api_server/services/tips.py", "services/tips", "tips"),
    ("api_server/services/title_gen.py", "services/ai", "title generation"),
    ("api_server/services/token_estimation.py", "services/ai", "token estimation"),
    ("api_server/services/tool_use_summary.py", "services/ai", "tool use summary"),
    ("api_server/services/tools_service.py", "services/tools", "tools service"),
    ("api_server/services/vcr.py", "services/vcr", "VCR"),
    ("api_server/services/voice.py", "services/voice", "voice service"),
    ("api_server/tools/__init__.py", "tools", "tools init"),
    ("api_server/tools/agent.py", "tools/agent", "agent tool"),
    ("api_server/tools/agent_tools.py", "tools/agent", "agent tools"),
    ("api_server/tools/ask_user_question.py", "tools/user", "ask user question"),
    ("api_server/tools/ask_user_tool.py", "tools/user", "ask user tool"),
    ("api_server/tools/bash.py", "tools/shell", "bash tool"),
    ("api_server/tools/brief.py", "tools/brief", "brief tool"),
    ("api_server/tools/brief_tool.py", "tools/brief", "brief tool"),
    ("api_server/tools/command_semantics.py", "tools/shell", "command semantics"),
    ("api_server/tools/config_tool.py", "tools/config", "config tool"),
    ("api_server/tools/cron_tool.py", "tools/cron", "cron tool"),
    ("api_server/tools/database_tool.py", "tools/database", "database tool"),
    ("api_server/tools/destructive_command_warning.py", "tools/shell", "destructive warning"),
    ("api_server/tools/executor.py", "tools/executor", "executor"),
    ("api_server/tools/file_tools.py", "tools/filesystem", "file tools"),
    ("api_server/tools/grep.py", "tools/search", "grep tool"),
    ("api_server/tools/list_mcp_resources_tool.py", "tools/mcp", "list MCP resources"),
    ("api_server/tools/lsp.py", "tools/lsp", "LSP tool"),
    ("api_server/tools/lsp_tool.py", "tools/lsp", "LSP tool"),
    ("api_server/tools/mcp_tool_registry.py", "tools/mcp", "MCP registry"),
    ("api_server/tools/mcp_tools.py", "tools/mcp", "MCP tools"),
    ("api_server/tools/memory_tools.py", "tools/memory", "memory tools"),
    ("api_server/tools/notebook_edit.py", "tools/notebook", "notebook edit"),
    ("api_server/tools/notebook_edit_tool.py", "tools/notebook", "notebook edit tool"),
    ("api_server/tools/notion_tools.py", "tools/notion", "notion tools"),
    ("api_server/tools/path_validation.py", "tools/security", "path validation"),
    ("api_server/tools/plan_mode_tools.py", "tools/plan", "plan mode tools"),
    ("api_server/tools/plan_tool.py", "tools/plan", "plan tool"),
    ("api_server/tools/powershell_security.py", "tools/shell", "PowerShell security"),
    ("api_server/tools/powershell_tool.py", "tools/shell", "PowerShell tool"),
    ("api_server/tools/read_mcp_resource_tool.py", "tools/mcp", "read MCP resource"),
    ("api_server/tools/read_only_validation.py", "tools/security", "read only validation"),
    ("api_server/tools/register.py", "tools", "tool registry"),
    ("api_server/tools/remote_trigger_tool.py", "tools/remote", "remote trigger"),
    ("api_server/tools/repl.py", "tools/repl", "REPL"),
    ("api_server/tools/report_tool.py", "tools", "report tool"),
    ("api_server/tools/review_tools.py", "tools/review", "review tools"),
    ("api_server/tools/schedule_cron_tool.py", "tools/cron", "schedule cron"),
    ("api_server/tools/send_message.py", "tools/agent", "send message"),
    ("api_server/tools/send_message_tool.py", "tools/agent", "send message tool"),
    ("api_server/tools/shell.py", "tools/shell", "shell tool"),
    ("api_server/tools/shell_permissions.py", "tools/shell", "shell permissions"),
    ("api_server/tools/shell_task.py", "tools/shell", "shell task"),
    ("api_server/tools/skill_tool.py", "tools/skills", "skill tool"),
    ("api_server/tools/sleep.py", "tools", "sleep"),
    ("api_server/tools/sleep_tool.py", "tools", "sleep tool"),
    ("api_server/tools/snip_tool.py", "tools", "snip tool"),
    ("api_server/tools/synthetic_output.py", "tools/ai", "synthetic output"),
    ("api_server/tools/synthetic_output_tool.py", "tools/ai", "synthetic output tool"),
    ("api_server/tools/task_create.py", "tools/task", "task create"),
    ("api_server/tools/task_get.py", "tools/task", "task get"),
    ("api_server/tools/task_list.py", "tools/task", "task list"),
    ("api_server/tools/task_output.py", "tools/task", "task output"),
    ("api_server/tools/task_stop.py", "tools/task", "task stop"),
    ("api_server/tools/task_tools.py", "tools/task", "task tools"),
    ("api_server/tools/task_update.py", "tools/task", "task update"),
    ("api_server/tools/team_tools.py", "tools/team", "team tools"),
    ("api_server/tools/todo_tool.py", "tools/todo", "todo tool"),
    ("api_server/tools/todo_write.py", "tools/todo", "todo write"),
    ("api_server/tools/tool_search.py", "tools/search", "tool search"),
    ("api_server/tools/tool_search_tool.py", "tools/search", "tool search tool"),
    ("api_server/tools/types.py", "tools", "tool types"),
    ("api_server/tools/verify_plan_tool.py", "tools/plan", "verify plan"),
    ("api_server/tools/web_fetch.py", "tools/web", "web fetch"),
    ("api_server/tools/workflow_tool.py", "tools/workflow", "workflow tool"),
    ("api_server/tools/worktree_tools.py", "tools/worktree", "worktree tools"),
    ("api_server/tools/web_search.py", "tools/web", "web search"),
    ("api_server/tools/web_tools.py", "tools/web", "web tools"),
    ("api_server/models/__init__.py", "models", "models init"),
    ("api_server/models/config.py", "models/config", "config model"),
    ("api_server/models/content_block.py", "models/content", "content block"),
    ("api_server/models/message.py", "models/message", "message model"),
    ("api_server/models/session.py", "models/session", "session model"),
    ("api_server/models/tool.py", "models/tool", "tool model"),
    ("api_server/adapters/__init__.py", "adapters", "adapters init"),
    ("api_server/adapters/anthropic.py", "adapters/llm", "Anthropic adapter"),
    ("api_server/adapters/base.py", "adapters/llm", "base adapter"),
    ("api_server/adapters/deepseek.py", "adapters/llm", "DeepSeek adapter"),
    ("api_server/adapters/minimax.py", "adapters/llm", "MiniMax adapter"),
    ("api_server/adapters/ollama.py", "adapters/llm", "Ollama adapter"),
    ("api_server/adapters/openai.py", "adapters/llm", "OpenAI adapter"),
    ("api_server/adapters/router.py", "adapters/llm", "router adapter"),
    ("api_server/agents/__init__.py", "agents", "agents init"),
    ("api_server/agents/loop.py", "agents/loop", "agent loop"),
    ("api_server/agents/task/registry.py", "agents/task", "task registry"),
    ("api_server/agents/task/types.py", "agents/task", "task types"),
    ("api_server/agents/teammate/backends.py", "agents/teammate", "teammate backends"),
    ("api_server/agents/teammate/executor.py", "agents/teammate", "teammate executor"),
    ("api_server/agents/teammate/iterm_backend.py", "agents/teammate", "iTerm backend"),
    ("api_server/agents/teammate/pane_executor.py", "agents/teammate", "pane executor"),
    ("api_server/agents/teammate/registry.py", "agents/teammate", "teammate registry"),
    ("api_server/agents/teammate/tmux_backend.py", "agents/teammate", "tmux backend"),
    ("api_server/agents/tool/execute.py", "agents/tool", "tool execute"),
    ("api_server/agents/tool/loop.py", "agents/tool", "tool loop"),
    ("api_server/agents/tool/mcp.py", "agents/tool", "MCP tool"),
    ("api_server/agents/tool/memory.py", "agents/tool", "memory tool"),
    ("api_server/agents/tool/registry.py", "agents/tool", "tool registry"),
    ("api_server/agents/tool/run_agent.py", "agents/tool", "run agent"),
    ("api_server/agents/tool/spawn.py", "agents/tool", "spawn"),
    ("api_server/agents/tool/built-in/claude_code_guide.py", "agents/tool", "Claude Code guide"),
    ("api_server/agents/tool/built-in/explore.py", "agents/tool", "explore agent"),
    ("api_server/agents/tool/built-in/general_purpose.py", "agents/tool", "general purpose"),
    ("api_server/agents/tool/built-in/plan.py", "agents/tool", "plan agent"),
    ("api_server/agents/tool/built-in/statusline_setup.py", "agents/tool", "statusline setup"),
    ("api_server/agents/tool/built-in/verification.py", "agents/tool", "verification agent"),
    ("api_server/sandbox/__init__.py", "sandbox", "sandbox init"),
    ("api_server/sandbox/config.py", "sandbox/config", "sandbox config"),
    ("api_server/sandbox/path_restrictions.py", "sandbox/security", "path restrictions"),
    ("api_server/sandbox/platform.py", "sandbox", "sandbox platform"),
    ("api_server/sandbox/sandboxed_shell.py", "sandbox", "sandboxed shell"),
    ("api_server/sandbox/adapters/base.py", "sandbox/adapters", "base adapter"),
    ("api_server/sandbox/adapters/bubblewrap.py", "sandbox/adapters", "bubblewrap"),
    ("api_server/sandbox/adapters/macos.py", "sandbox/adapters", "macOS"),
    ("api_server/sandbox/adapters/noop.py", "sandbox/adapters", "noop"),
    ("api_server/sandbox/adapters/windows.py", "sandbox/adapters", "Windows"),
    ("api_server/sandbox/adapters/wsl2.py", "sandbox/adapters", "WSL2"),
    ("api_server/ws/__init__.py", "ws", "WebSocket init"),
    ("api_server/ws/agent_summary_ws.py", "ws", "agent summary WS"),
    ("api_server/ws/auto_dream_ws.py", "ws", "auto dream WS"),
    ("api_server/ws/bridge_ws.py", "ws", "bridge WS"),
    ("api_server/ws/protocol.py", "ws/protocol", "WS protocol"),
    ("api_server/ws/chat.py", "ws/chat", "chat WS"),
    ("api_server/lsp/__init__.py", "lsp", "LSP init"),
    ("api_server/lsp/client.py", "lsp/client", "LSP client"),
    ("api_server/lsp/config.py", "lsp/config", "LSP config"),
    ("api_server/lsp/manager.py", "lsp/manager", "LSP manager"),
    ("api_server/lsp/operations.py", "lsp/operations", "LSP operations"),
    ("api_server/lsp/server_instance.py", "lsp/server", "LSP server"),
    ("api_server/lsp/server_manager.py", "lsp/server", "LSP server manager"),
    ("api_server/lsp/types.py", "lsp/types", "LSP types"),
]

for path, category, summary in python_files:
    db.execute("""
        INSERT INTO python_files (python_path, category, summary, status)
        VALUES (?, ?, ?, 'pending')
    """, (path, category, summary))

db.commit()

count = db.execute("SELECT COUNT(*) FROM python_files").fetchone()[0]
print(f"Inserted {count} Python files")

total_ts = db.execute("SELECT COUNT(*) FROM files").fetchone()[0]
total_py = db.execute("SELECT COUNT(*) FROM python_files").fetchone()[0]
print(f"Total files: {total_ts} TypeScript + {total_py} Python = {total_ts + total_py}")

db.close()